name: btc_sdk
description: Library to use Bitcoin with Dart and Flutter applications
version: 0.1.3
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - bitcoin
  - btc
  - sdk
  - crypto
  - library
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  crypto: ^3.0.2
  equatable: ^2.0.5
  fast_base58: ^0.2.1
  hex: ^0.2.0
  pointycastle: ^3.6.2
  stack: ^0.2.1

documentation: "https://github.com/patricknoir/btc_sdk/blob/master/docs/Index.md"
repository: "https://github.com/patricknoir/btc_sdk"
